# Generated by Django 4.0.3 on 2022-07-12 15:32

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_cat', models.CharField(max_length=100)),
                ('parent_cat_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='parent_cat', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Parent Categories',
                'db_table': 'app_parent_category',
            },
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_cat', models.CharField(max_length=100)),
                ('child_cat_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='child_cat', unique=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parentcategory')),
            ],
            options={
                'verbose_name_plural': 'Child Categories',
                'db_table': 'app_child_category',
            },
        ),
    ]
