# Generated by Django 4.0.3 on 2022-07-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('child_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.childcategory')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parentcategory')),
            ],
        ),
    ]
