# Generated by Django 4.0.3 on 2022-06-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_two', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
