# Generated by Django 4.0.3 on 2022-06-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.EmailField(max_length=100)),
                ('stu_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
