# Generated by Django 4.0.3 on 2022-06-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_comment',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
