# Generated by Django 4.0.3 on 2022-06-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_data_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
