# Generated by Django 4.0.3 on 2022-05-13 05:18

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.FileField(default=None, max_length=255, null=True, upload_to='blog/')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_title', unique=True)),
                ('blog_desc', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='PageTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_page_title', models.CharField(max_length=50)),
            ],
        ),
    ]
