# Generated by Django 4.0.3 on 2022-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcategory',
            name='is_active',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
