# Generated by Django 4.0.3 on 2022-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Azad Jammu and Kashmir', 'Azad Jammu and Kashmir'), ('Balochistan', 'Balochistan'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Islamabad Capital Territory', 'Islamabad Capital Territory'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Punjab', 'Punjab'), ('Sindh', 'Sindh')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('moblie', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='profile-image')),
                ('upload_cv', models.ImageField(upload_to='cv')),
            ],
        ),
    ]
