# Generated by Django 4.0.3 on 2022-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='upload_cv',
            field=models.FileField(upload_to='cv'),
        ),
    ]
